apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwggu9967-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwggu9967-tenant-component
    app.kubernetes.io/part-of: loadwggu9967-tenant-app
  name: loadwggu9967-tenant-component
  namespace: loadwggu9967-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadwggu9967-tenant-component
    weight: null
status: {}
